from colorama import Fore, Back, Style

print("")
print("")
print(f'{Fore.WHITE}$ git log')
print(f'{Fore.YELLOW}commit 83b967c04c445b5cea11bc0aed78acce9987553b ({Fore.CYAN}{Style.BRIGHT}HEAD -> {Fore.GREEN}master{Fore.YELLOW}{Style.NORMAL}, {Fore.GREEN}{Style.BRIGHT}test{Fore.YELLOW}{Style.NORMAL})')
print(f'{Fore.WHITE}Author: Jeremy Goff <jeremygoff03@gmail.com>')
print(f'{Fore.WHITE}Date:   Tus Nov 28 19:12:38 2023 -0500')
print("")
print(f'{Fore.WHITE}     Added data importing')
print("")
print(f'{Fore.YELLOW}commit 2c042d4689cc06f798041b888b0819fb21d41938 ({Fore.CYAN}{Style.BRIGHT}HEAD -> {Fore.GREEN}master{Fore.YELLOW}{Style.NORMAL}, {Fore.GREEN}{Style.BRIGHT}test{Fore.YELLOW}{Style.NORMAL})')
print(f'{Fore.WHITE}Author: Jeremy Goff <jeremygoff03@gmail.com>')
print(f'{Fore.WHITE}Date:   Tus Nov 28 21:31:14 2023 -0500')
print("")
print(f'{Fore.WHITE}     Added data cleaning')
print("")
print(f'{Fore.YELLOW}commit 9cffe506ad550fdab0952ba6adf84466fd853738 ({Fore.CYAN}{Style.BRIGHT}HEAD -> {Fore.GREEN}master{Fore.YELLOW}{Style.NORMAL}, {Fore.GREEN}{Style.BRIGHT}test{Fore.YELLOW}{Style.NORMAL})')
print(f'{Fore.WHITE}Author: Jeremy Goff <jeremygoff03@gmail.com>')
print(f'{Fore.WHITE}Date:   Thu Nov 30 17:06:52 2023 -0500')
print("")
print(f'{Fore.WHITE}     Fixed formatting issues and updated data interface')
print("")

print("")
print("")
print(f'{Fore.WHITE}$ git log')
print(f'{Fore.YELLOW}commit 1de8c72ccc29328abe817e8372c9213b49459094 ({Fore.CYAN}{Style.BRIGHT}HEAD -> {Fore.GREEN}test{Fore.YELLOW}{Style.NORMAL})')
print(f'{Fore.WHITE}Author: Jeremy Goff <jeremygoff03@gmail.com>')
print(f'{Fore.WHITE}Date:   Fri Dec 1 22:43:17 2023 -0500')
print("")
print(f'{Fore.WHITE}     Added visualzation for model and data')
print("")